const actionTypes = {

    /** GLOBAL */
    RESET_MESSAGE: 'RESET_MESSAGE',

    /** CATEGORY */
    GET_CATEGORY_ERR: 'GET_CATEGORY_ERR',
    GET_CATEGORY: 'GET_CATEGORY_ERR',
    GET_CATEGORY_EDIT: 'GET_CATEGORY_EDIT',
    GET_CATEGORY_EDIT_ERR : 'GET_CATEGORY_EDIT_ERR',
    UPDATE_CATEGORY: 'UPDATE_CATEGORY',
    UPDATE_CATEGORY_ERR: 'UPDATE_CATEGORY_ERR',
    ADD_CATEGORY_ERR: 'ADD_CATEGORY_ERR',
    ADD_CATEGORY: 'ADD_CATEGORY',
    DELETE_CATEGORY: 'DELETE_CATEGORY',
    DELETE_CATEGORY_ERR: 'DELETE_CATEGORY_ERR',
    DELETE_MANY_CATEGORY: 'DELETE_MANY_CATEGORY',
    DELETE_MANY_CATEGORY_ERR: 'DELETE_MANY_CATEGORY_ERR',

    /** STORE */
    GET_STORE_ERR: 'GET_STORE_ERR',
    GET_STORE: 'GET_STORE_ERR',
    ADD_STORE_ERR: 'ADD_STORE_ERR',
    ADD_STORE: 'ADD_STORE',
    DELETE_STORE: 'DELETE_STORE',
    DELETE_STORE_ERR: 'DELETE_STORE_ERR',
    DELETE_MANY_STORE_ERR: 'DELETE_MANY_STORE_ERR',
    DELETE_MANY_STORE: 'DELETE_MANY_STORE',
    GET_STORE_EDIT: 'GET_STORE_EDIT',
    GET_STORE_EDIT_ERR: 'GET_STORE_EDIT_ERR',
    UPDATE_STORE_ERR: 'UPDATE_STORE_ERR',
    UPDATE_STORE: 'UPDATE_STORE',
    FILTER_STORE_ERR: 'FILTER_STORE_ERR',
    FILTER_STORE: 'FILTER_STORE',

    /** OFFER */
    ADD_OFFER_ERR: 'ADD_OFFER_ERR',
    ADD_OFFER: 'ADD_OFFER',
    GET_OFFER_ERR: 'GET_OFFER_ERR',
    GET_OFFER: 'GET_OFFER',
    GET_OFFER_EDIT_ERR: 'GET_OFFER_EDIT_ERR',
    GET_OFFER_EDIT: 'GET_OFFER_EDIT',
    UPDATE_OFFER: 'UPDATE_OFFER',
    UPDATE_OFFER_ERR: 'UPDATE_OFFER_ERR',
    DELETE_OFFER_ERR: 'DELETE_OFFER_ERR',
    DELETE_OFFER: 'DELETE_OFFER',
    DELETE_MANY_OFFER: 'DELETE_MANY_OFFER',
    DELETE_MANY_OFFER_ERR: 'DELETE_MANY_OFFER',
    FILTER_OFFER_ERR: 'FILTER_OFFER_ERR',
    FILTER_OFFER: 'FILTER_OFFER'
}

export default actionTypes